### ISSUE TITLE
CT nefunguje :(

### ISSUE THREAD

**Issue by ghost** [Limoto/tv-dl#10]
A nemůžou to nechat, tak jak to je, musej do toho pořád vrtat...

```
C:\Users\halfman\Projects\tv-dl>python tv-dl http://www.ceskatelevize.cz/ivysilani/10389601973-denik-tobruk/21238255344/ -D

 Arguments:
 * URL = http://www.ceskatelevize.cz/ivysilani/10389601973-denik-tobruk/21238255344/
 * get_url = False
 * loglevel = 10
 * movie = None
 * output = None
 * quality = None

Traceback (most recent call last):
  File "tv-dl", line 123, in <module>
    downloader.main()
  File "tv-dl", line 29, in main
    e = self.get_engine(self.args.URL)[2](self.args.URL)
  File "C:\Users\halfman\Projects\tv-dl\engines\ct.py", line 69, in __init__
    pl_url = urlopen(req).read().decode('utf-8')
  File "C:\Python32\lib\urllib\request.py", line 138, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python32\lib\urllib\request.py", line 375, in open
    response = meth(req, response)
  File "C:\Python32\lib\urllib\request.py", line 487, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python32\lib\urllib\request.py", line 413, in error
    return self._call_chain(*args)
  File "C:\Python32\lib\urllib\request.py", line 347, in _call_chain
    result = func(*args)
  File "C:\Python32\lib\urllib\request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Limoto** [comment]
Dík za nahlášení, opraveno.

**Comment by ghost** [comment]
Díky.
