### ISSUE TITLE
ct engine

### ISSUE THREAD

**Issue by the-only-neo** [Limoto/tv-dl#29]
tv-dl -q list http://www.ceskatelevize.cz/porady/10431595237-ctvrta-hvezda/video/

Traceback (most recent call last):
  File "/usr/bin/tv-dl", line 123, in <module>
    downloader.main()
  File "/usr/bin/tv-dl", line 29, in main
    e = self.get_engine(self.args.URL)[2](self.args.URL)
  File "/sources/git-repo/tv-dl/engines/ct.py", line 72, in **init**
    self.playlist = urlopen(pl_url).read().decode('utf-8')
  File "/usr/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib/python3.3/urllib/request.py", line 492, in _open
    'unknown_open', req)
  File "/usr/lib/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 1310, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: uri>http>

**Comment by okias** [comment]
in this moment output equals to bug #30

**Comment by Limoto** [comment]
Opraveno (viz #31)
